STATUS_IDLE = 0
STATUS_ORDER_RECEIVED = 10
STATUS_PROCESS_START = 20
STATUS_MOVE_TO_PERFUME = 30
STATUS_CHECK_PERFUME = 40
STATUS_OPEN_PERFUME_LID = 50
STATUS_STORE_PERFUME_LID = 60

STATUS_SCENT_PROCESS_START = 100
STATUS_MOVE_TO_SCENT = 110
STATUS_EXTRACT_SCENT = 120
STATUS_GRIP_SCENT_LID = 130
STATUS_OPEN_SCENT_LID = 140
STATUS_MOVE_TO_MIX_BOTTLE = 150
STATUS_DISPENSE_SCENT = 160
STATUS_GRIP_SCENT_LID_RETURN = 170
STATUS_RETURN_TO_SCENT = 180
STATUS_CLOSE_SCENT_LID = 190
STATUS_SCENT_PROCESS_DONE = 200

STATUS_GET_PERFUME_LID = 210
STATUS_MOVE_LID_TO_PERFUME = 220
STATUS_CLOSE_PERFUME_LID = 230
STATUS_GRIP_FINISHED_PERFUME = 240
STATUS_MOVE_TO_HOME = 250
STATUS_SHAKE_PERFUME = 260
STATUS_TILT_MIX_PERFUME = 270
STATUS_MOVE_TO_PICKUP = 280
STATUS_PLACE_PERFUME = 290
STATUS_RELEASE_PERFUME = 300
STATUS_PROCESS_COMPLETE = 310
STATUS_RETURN_HOME = 320
STATUS_READY = 330


# 콘솔에서 상태 번호와 이름을 함께 확인하기 위한 용도
STATUS_NAMES = {
    STATUS_IDLE: "IDLE",
    STATUS_ORDER_RECEIVED: "ORDER_RECEIVED",
    STATUS_PROCESS_START: "PROCESS_START",
    STATUS_MOVE_TO_PERFUME: "MOVE_TO_PERFUME",
    STATUS_CHECK_PERFUME: "CHECK_PERFUME",
    STATUS_OPEN_PERFUME_LID: "OPEN_PERFUME_LID",
    STATUS_STORE_PERFUME_LID: "STORE_PERFUME_LID",

    STATUS_SCENT_PROCESS_START: "SCENT_PROCESS_START",
    STATUS_MOVE_TO_SCENT: "MOVE_TO_SCENT",
    STATUS_EXTRACT_SCENT: "EXTRACT_SCENT",
    STATUS_GRIP_SCENT_LID: "GRIP_SCENT_LID",
    STATUS_OPEN_SCENT_LID: "OPEN_SCENT_LID",
    STATUS_MOVE_TO_MIX_BOTTLE: "MOVE_TO_MIX_BOTTLE",
    STATUS_DISPENSE_SCENT: "DISPENSE_SCENT",
    STATUS_GRIP_SCENT_LID_RETURN: "GRIP_SCENT_LID_RETURN",
    STATUS_RETURN_TO_SCENT: "RETURN_TO_SCENT",
    STATUS_CLOSE_SCENT_LID: "CLOSE_SCENT_LID",
    STATUS_SCENT_PROCESS_DONE: "SCENT_PROCESS_DONE",

    STATUS_GET_PERFUME_LID: "GET_PERFUME_LID",
    STATUS_MOVE_LID_TO_PERFUME: "MOVE_LID_TO_PERFUME",
    STATUS_CLOSE_PERFUME_LID: "CLOSE_PERFUME_LID",
    STATUS_GRIP_FINISHED_PERFUME: "GRIP_FINISHED_PERFUME",
    STATUS_MOVE_TO_HOME: "MOVE_TO_HOME",
    STATUS_SHAKE_PERFUME: "SHAKE_PERFUME",
    STATUS_TILT_MIX_PERFUME: "TILT_MIX_PERFUME",
    STATUS_MOVE_TO_PICKUP: "MOVE_TO_PICKUP",
    STATUS_PLACE_PERFUME: "PLACE_PERFUME",
    STATUS_RELEASE_PERFUME: "RELEASE_PERFUME",
    STATUS_PROCESS_COMPLETE: "PROCESS_COMPLETE",
    STATUS_RETURN_HOME: "RETURN_HOME",
    STATUS_READY: "READY",
}